unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# https://github.com/christoomey/vim-tmux-navigator/issues/230#issuecomment-1609156039
unbind -T copy-mode-vi MouseDragEnd1Pane

set -g mouse on

# tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# catppuccin theme (v2) - must be loaded before other plugins
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'frappe'
set -g @catppuccin_window_text " #{pane_current_command}"
set -g @catppuccin_window_current_text " #{pane_current_command}"
set -g @catppuccin_window_current_background "#{@thm_mauve}"
set -g status-right "#{E:@catppuccin_status_session}"
set -g status-left ""

# navigate panes and vim/nvim with Ctrl-hjkl
set -g @plugin 'christoomey/vim-tmux-navigator'

# persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'

# automatically saves sessions every 15 minutes
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Initialize tmux plugin manager (keep this line at the bottom)
run '~/.tmux/plugins/tpm/tpm'